In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
# from matplotlib import pyplot as plt

In [21]:
scores = [94,122,211,126,1,124,74,111,187,157,36,37]

df = pd.read_csv("blee.csv", names=['Loops','Ifs','Returns','nested','rowcount'])
features = ['Loops','Ifs','Returns','nested','rowcount']
# Separating out the features
x = df.loc[:, features].values
x

array([[ 5,  1,  0,  1,  0],
       [ 8,  1,  1,  2,  0],
       [10,  1,  2,  1,  1],
       [10,  0,  2,  5,  0],
       [12,  0,  0,  2,  0],
       [13,  0,  3,  4,  1],
       [11,  1,  2,  1,  1],
       [ 5,  1,  1,  2,  1],
       [ 7,  1,  1,  1,  1],
       [ 6,  1,  1,  1,  1],
       [ 7,  1,  2,  1,  2],
       [ 5,  1,  1,  2,  1]])

In [18]:
# Separating out the target
# y = df.loc[:,['Class']].values
# Standardizing the features
# ??
xs = StandardScaler().fit_transform(x)  
xs

array([[-1.18508739,  0.57735027, -1.56892908, -0.73009564, -1.26025208],
       [-0.09116057,  0.57735027, -0.39223227,  0.06637233, -1.26025208],
       [ 0.63812398,  0.57735027,  0.78446454, -0.73009564,  0.42008403],
       [ 0.63812398, -1.73205081,  0.78446454,  2.45577625, -1.26025208],
       [ 1.36740853, -1.73205081, -1.56892908,  0.06637233, -1.26025208],
       [ 1.73205081, -1.73205081,  1.96116135,  1.65930828,  0.42008403],
       [ 1.00276626,  0.57735027,  0.78446454, -0.73009564,  0.42008403],
       [-1.18508739,  0.57735027, -0.39223227,  0.06637233,  0.42008403],
       [-0.45580284,  0.57735027, -0.39223227, -0.73009564,  0.42008403],
       [-0.82044512,  0.57735027, -0.39223227, -0.73009564,  0.42008403],
       [-0.45580284,  0.57735027,  0.78446454, -0.73009564,  2.10042013],
       [-1.18508739,  0.57735027, -0.39223227,  0.06637233,  0.42008403]])

In [19]:
pca = PCA(n_components=1)
pC1 = pca.fit_transform(x)
pC1Df = pd.DataFrame(data = pC1, columns = ['unscaled'])
pC1Df

    unscaled
0  -3.522258
1  -0.272769
2   1.514217
3   2.618240
4   3.481124
5   5.355163
6   2.464154
7  -3.159880
8  -1.497639
9  -2.447576
10 -1.372895
11 -3.159880

In [20]:
pC2 = pca.fit_transform(xs)
pC2Df = pd.DataFrame(data = pC2, columns = ['scaled'])
pC2Df
# finalDf = pd.concat([principalDf, df[['Class']]], axis = 1)

# fig = plt.figure(figsize = (8,8))
# ax = fig.add_subplot(1,1,1) 
# ax.set_xlabel('Principal Component 1', fontsize = 15)
# ax.set_ylabel('Principal Component 2', fontsize = 15)
# #ax.set_title('2 component PCA', fontsize = 20)
# targets = ['CONFUSING','CLEAR']
# colors = ['black','darkgray','g']

# for target, color in zip(targets,colors):
#     indicesToKeep = finalDf['Class'] == target
#     ax.scatter(finalDf.loc[indicesToKeep, 'principal component 1']
#                , finalDf.loc[indicesToKeep, 'principal component 2']
#                , c = color
#                , s = 50)
# """
# for i in range (len(principalDf)):
#     ax.scatter(principalDf.loc[i, 'principal component 1']
#                , principalDf.loc[i, 'principal component 2']
#                , c = 'b'
#                , s = 50)
# #ax.legend(targets)
# """
# ax.legend(targets)
# ax.grid()
# plt.savefig('pca2.pdf',bbox_inches='tight')
# plt.show()

      scaled
0  -1.510429
1  -0.183782
2  -0.255480
3   3.128914
4   1.515576
5   3.240359
6  -0.072337
7  -1.098034
8  -1.156938
9  -1.340081
10 -1.169733
11 -1.098034